name: flutter_wioso
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  wave: ^0.2.2
  hexcolor: ^2.0.7
  google_fonts: ^3.0.1
  flutter_map: ^2.2.0
  sliding_up_panel: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
